### ISSUE TITLE
"Then" clause failures produce a stack trace instead of useful error message

### ISSUE THREAD

**Issue by purple52** [CJSCommonPlatform/domain-test-dsl#8]
If a "Then" (or subsequent "And") does not match an event, it should report what event (if any) was found instead of the one expected. Currently, if no event is found, the following stack trace is emitted instead:

Then hearing allocated for listing                                                                                          # DomainTestSteps.previous_events(String)
     java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
         at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
         at java.util.LinkedList.get(LinkedList.java:476)
         at uk.gov.justice.services.test.domain.DomainTestSteps.assert_events_generated(DomainTestSteps.java:54)
         at uk.gov.justice.services.test.domain.DomainTestSteps.previous_events(DomainTestSteps.java:32)
         at ✽.Then hearing allocated for listing(allocate-hearing.feature:28)

**Comment by purple52** [comment]
Fixed by #12
